
name: Burnmoor Chase
views:
- icon: mdi:home
  title: Home
  id: home
  cards:

    - type: entities
      title: Family
      show_header_toggle: false
      entities:
        - entity: device_tracker.amysiphone
          name: Amy's iPhone
        - entity: device_tracker.google_maps_113840736270482299573
          name: Bill's Google Maps
        - entity: device_tracker.oneplus_6
          name: Bill's Phone
        - entity: binary_sensor.bill
          name: Bill Binary Sensor

    - type: entity-filter
      entities:
        - device_tracker.gstharveysiphone
        - device_tracker.gstjillsiphone
        - device_tracker.gstsamsunggalaxys7
        - device_tracker.gstgalaxys6
        - device_tracker.gstailsasipodtouch
        - device_tracker.gstoneplusone
        - device_tracker.gstnexus6p
        - device_tracker.gstoneplus_5
        - device_tracker.gstoneplus_5_2
        - device_tracker.gstoneplus_5_3
      state_filter: 
        - home
      show_empty: true
      card:
        type: glance
        title: Guest's at Home

    - type: glance
      title: Home Devices
      entities:
        - entity: light.porch_light
          name: Porch

    - type: picture-entity
      title: Living Room Camera
      entity: camera.camera_1
      camera-image: camera.camera_1
      show_info: false

    - type: entities
      title: Climate
      show_header_toggle: false
      entities:
        - device_tracker.nest_hub
        - binary_sensor.downstairs_thermostat_online
        - climate.downstairs
        - sensor.downstairs_thermostat_humidity
        - binary_sensor.downstairs_thermostat_has_leaf

    - type: entities
      title: Travel Times
      show_header_toggle: false
      entities:
        - sensor.amy_home_to_work
        - sensor.amy_waze_to_work
        - sensor.bill_home_to_work
        - sensor.bill_waze_to_work

    - type: entities
      title: Weather Forecast
      show_header_toggle: false
      entities:
        - sun.sun
        - sensor.dark_sky_hourly_summary
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature

    - type: entities
      title: Lighting
      show_header_toggle: false
      entities:
        - input_select.lights
        - input_select.light_sets
        - input_number.light_temp
        - input_number.light_brightness
        - script.set_lighting


- icon: mdi:sofa
  title: Living Room
  id: living_room
  cards:

    - type: entities
      title: Lighting
      show_header_toggle: false
      entities:
        - switch.scentsy
        - switch.living_room_lamp

    - type: entities
      title: Media Devices
      show_header_toggle: false
      entities:
        - device_tracker.googlelounge
        - device_tracker.ps4
        - device_tracker.sky_q_box
        - device_tracker.amysipad

    - type: entities
      title: Internet Radio
      show_header_toggle: false
      entities:
        - input_select.radio_station
        - input_select.speakers
        - input_number.volume_radio
        - script.net_radio

    - type: media-control
      entity: media_player.living_room_speaker

    - type: entities
      title: Lounge Automations
      show_header_toggle: false
      entities:
        - automation.home_time
    #    - automation.home_time_end_dumb
        - automation.home_time_end
        - automation.lamp_light_on
        - automation.lamp_light_off

    - type: picture-entity
      title: Living Room Camera
      entity: camera.camera_1
      camera-image: camera.camera_1
      show_info: false

- icon: mdi:hotel
  title: Bedroom
  id: bedroom
  cards:

    - type: entities
      title: Bedroom
      show_header_toggle: false
      entities:
        - device_tracker.googlebed
        - light.amy_bedside_light
        - light.bill_bedside_light

    - type: entities
      title: Bedroom Automation
      show_header_toggle: false
      entities:
        - automation.wakeup_time
        - automation.morning_radio
        - automation.morning_radio_2

    - type: entities
      title: Weather Forecast
      show_header_toggle: false
      entities:
        - sun.sun
        - sensor.dark_sky_hourly_summary
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature

    - type: entities
      title: Internet Radio
      show_header_toggle: false
      entities:
        - input_select.radio_station
        - input_select.speakers
        - input_number.volume_radio
        - script.net_radio

    - type: entities
      title: Lighting
      show_header_toggle: false
      entities:
        - input_select.lights
        - input_select.light_sets
        - input_number.light_temp
        - input_number.light_brightness
        - script.set_lighting

    - type: media-control
      entity: media_player.bedroom_speaker


- icon: mdi:bed-empty
  title: Guest Bedroom
  id: guest_bedroom
  cards:

    - type: entity-filter
      entities:
        - device_tracker.gstharveysiphone
        - device_tracker.gstjillsiphone
        - device_tracker.gstsamsunggalaxys7
        - device_tracker.gstgalaxys6
        - device_tracker.gstailsasipodtouch
        - device_tracker.gstoneplusone
        - device_tracker.gstnexus6p
        - device_tracker.gstoneplus_5
        - device_tracker.gstoneplus_5_2
        - device_tracker.gstoneplus_5_3
      state_filter: 
        - home
      show_empty: true
      card:
        type: glance
        title: Guest's at Home

    - type: entities
      title: Guest Bedroom
      show_header_toggle: false
      entities:
        - device_tracker.toshibatv
        - device_tracker.youview
        - device_tracker.chromecast1

    - type: media-control
      entity: media_player.guest_room_chromecast

- icon: mdi:cat
  title: Cat
  id: cat
  cards:

    - type: entities
      title: Cat Devices
      show_header_toggle: false
      entities:
        - device_tracker.sureflap_hub
        - device_tracker.space_heater
        - switch.space_heater

    - type: entities
      title: Cat Automations
      show_header_toggle: false
      entities:
        - automation.cat_am_on
        - automation.cat_am_off
        - automation.cat_pm_on
        - automation.cat_pm_off
        - automation.cat_timeout

    - type: entities
      title: Weather Forecast
      show_header_toggle: false
      entities:
        - sun.sun
        - sensor.dark_sky_hourly_summary
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature

- icon: mdi:flower
  title: Garden
  id: garden
  cards:

    - type: entities
      title: Garden Devices
      show_header_toggle: false
      entities:
        - device_tracker.googlehome

    - type: entities
      title: Weather Forecast
      show_header_toggle: false
      entities:
        - sun.sun
        - sensor.dark_sky_hourly_summary
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature

    - type: media-control
      entity: media_player.back_garden_speaker

    - type: entities
      title: Internet Radio
      show_header_toggle: false
      entities:
        - input_select.radio_station
        - input_select.speakers
        - input_number.volume_radio
        - script.net_radio

- icon: mdi:weather-partlycloudy
  title: Weather
  id: weather
  cards:

    - type: entities
      title: Weather Forecast
      show_header_toggle: false
      entities:
        - sun.sun
        - sensor.dark_sky_hourly_summary
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature

    - type: entities
      title: Weather Detail
      show_header_toggle: false
      entities:
        - sensor.weather_symbol
        - sensor.dark_sky_icon
        - sensor.dark_sky_summary
        - sensor.weather_temperature
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature
        - sensor.dark_sky_nearest_storm_distance
        - sensor.weather_cloudiness
        - sensor.weather_pressure
        - sensor.dark_sky_wind_speed
        - sensor.weather_wind_speed
        - sensor.weather_wind_direction
        - sensor.weather_precipitation
        - sensor.weather_humidity
        - sensor.weather_dewpoint_temperature
        - sensor.weather_fog
        - sensor.weather_low_clouds
        - sensor.weather_medium_clouds
        - sensor.weather_high_clouds

    - type: entities
      title: Climate Full
      show_header_toggle: false
      entities:
        - device_tracker.nest_hub
        - binary_sensor.downstairs_thermostat_online
        - climate.downstairs
        - sensor.downstairs_thermostat_target
        - sensor.downstairs_thermostat_temperature
        - sensor.downstairs_thermostat_humidity
        - sensor.downstairs_thermostat_operation_mode
        - sensor.downstairs_thermostat_hvac_state
        - binary_sensor.downstairs_thermostat_fan
        - binary_sensor.downstairs_thermostat_has_leaf
        - binary_sensor.downstairs_thermostat_is_locked
        - binary_sensor.downstairs_thermostat_is_using_emergency_heat

- icon: mdi:home-assistant
  title: Smart Home
  id: smart_home
  cards:

    - type: entities
      title: Smart Devices
      show_header_toggle: false
      entities:
        - device_tracker.nest_hub
        - device_tracker.bill_honor_7
        - device_tracker.hik_cam1_wifi
    #    - device_tracker.lr_lamp
    #    - device_tracker.sonoff_scentsy
    #    - device_tracker.dash_finish
    #    - device_tracker.dash_fairy

    - type: entities
      title: Access
      show_header_toggle: false
      entities:
        - binary_sensor.ip_camera_pir_alarm_2
        - binary_sensor.pir_sensor
        - binary_sensor.front_door
        - binary_sensor.hall_door
        - binary_sensor.other_door

    - type: entities
      title: Home Automations
      show_header_toggle: false
      entities:
        - automation.front_door_on
        - automation.front_door_off
        - automation.front_door_timeout

    - type: entities
      title: Media Automations
      show_header_toggle: false
      entities:
        - automation.volume_wake_up
        - automation.volume_up
        - automation.volume_down

- icon: mdi:laptop-windows
  title: IT
  id: it
  cards:

    - type: entities
      title: Network Devices
      show_header_toggle: false
      entities:
    #    - device_tracker.williamenvy
        - device_tracker.williamenvy_2
        - device_tracker.mycloudex2ultra
        - device_tracker.sky_q_hub
        - device_tracker.sthub
        - device_tracker.adminsmbp

    - type: entities
      title: Internet Tests
      show_header_toggle: false
      entities:
        - sensor.speedtest_download
        - sensor.speedtest_upload
        - sensor.speedtest_ping

    - type: entities
      title: Admin Automations
      show_header_toggle: false
      entities:
        - automation.snapshot
        - automation.snapshot_upload_dropbox


- icon: mdi:settings
  title: Technical
  id: technical
  cards:

    - type: entities
      title: Access Details
      show_header_toggle: false
      entities:
        - sensor.pir_sensor_illuminance
        - sensor.pir_sensor_battery
        - sensor.front_door_battery
        - sensor.hall_door_battery
        - sensor.other_door_battery

    - type: entities
      title: Climate Full
      show_header_toggle: false
      entities:
        - device_tracker.nest_hub
        - binary_sensor.downstairs_thermostat_online
        - climate.downstairs
        - sensor.downstairs_thermostat_target
        - sensor.downstairs_thermostat_temperature
        - sensor.downstairs_thermostat_humidity
        - sensor.downstairs_thermostat_operation_mode
        - sensor.downstairs_thermostat_hvac_state
        - binary_sensor.downstairs_thermostat_fan
        - binary_sensor.downstairs_thermostat_has_leaf
        - binary_sensor.downstairs_thermostat_is_locked
        - binary_sensor.downstairs_thermostat_is_using_emergency_heat

    - type: entities
      title: Access Details
      show_header_toggle: false
      entities:
        - group.all_automations