###Conventional Sensors Go Here###

#Weather prediction
- platform: yr
  name: Weather
  icon: mdi:weather-partlycloudy
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: darksky
  api_key: !secret dark_sky_api_key
  units: uk2
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - hourly_summary
    - temperature
    - precip_probability
    - wind_speed
    - temperature_low
    - temperature_high


- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

#- platform: google_travel_time
#  name: Bill Home to Work
#  icon: mdi:google-maps
#  api_key: !secret gtt_api_key
#  origin: !secret home_addr
#  destination: !secret Bwork_addr

#- platform: google_travel_time
#  name: Amy Home to Work
#  icon: mdi:google-maps
#  api_key: !secret gtt_api_key
#  origin: !secret home_addr
#  destination: !secret Awork_addr

- platform: waze_travel_time
  name: Bill Waze to Work
  origin: !secret home_addr
  destination: !secret Bwork_addr
  region: 'EU'

- platform: waze_travel_time
  name: Amy Waze to Work
  origin: !secret home_addr
  destination: !secret Awork_addr
  region: 'EU'

###Xiaomi Temp Probes###
- platform: mqtt
  name: "Bedroom Temp"
  state_topic: "smartthings/Xiaomi Temp Probe #1/temperature/state"
  device_class: thermometer
  unit_of_measurement: '°C'

- platform: mqtt
  name: "Bedroom Temp"
  state_topic: "smartthings/Xiaomi Temp Probe #2/thermometer/state"
  device_class: thermometer
  unit_of_measurement: 'C'

- platform: mqtt
  name: "Bedroom Temp"
  state_topic: "smartthings/Xiaomi Temp Probe #1/humidity/state"
  device_class: humidity
  unit_of_measurement: '%'

- platform: mqtt
  name: "Bedroom Temp"
  state_topic: "smartthings/Xiaomi Temp Probe #1/humidity/state"
  device_class: humidity
  unit_of_measurement: '%'

###Xiaomi Battery Levels###
- platform: mqtt
  name: "Front Door Battery"
  state_topic: "smartthings/Door Sensor 1 (Front)/battery/state"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "Hall Door Battery"
  state_topic: "smartthings/Door Sensor 2 (Hall)/battery/state"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "Other Door Battery"
  state_topic: "smartthings/Door Sensor 3/battery/state"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "PIR Sensor Battery"
  state_topic: "smartthings/PIR Motion Sensor/battery/state"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "PIR Sensor Illuminance"
  state_topic: "smartthings/PIR Motion Sensor/illuminance/state"
  device_class: illuminance
  unit_of_measurement: 'lx'

- platform: mqtt
  name: "Front Door PIR Sensor Battery"
  state_topic: "smartthings/Front Door PIR Sensor/battery/state"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "Bedroom Temp Probe Battery"
  state_topic: "smartthings/Xiaomi Temp Probe #1/battery/state"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "Conservatory Temp Probe Battery"
  state_topic: "smartthings/Xiaomi Temp Probe #2/battery/state"
  device_class: battery
  unit_of_measurement: '%'
