###AM Routines ###

###Morning Alarms###
- alias: Morning Radio
  trigger:
    - platform: time
      at: '06:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: '0.12'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_one.m3u8
        media_content_type: 'application/x-mpegurl'

- alias: Wake-Up Time
  trigger:
    - platform: time
      at: '06:56:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: '0.25'
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data_template:
        message: 'Good morning Amy & Bill. The Weather forecast is {{states.sensor.dark_sky_hourly_summary.state}}, the temperature outside is currently {{states.sensor.weather_temperature.state|round}} degrees, with a high today of {{states.sensor.dark_sky_daytime_high_temperature.state|round}} degrees and a low of {{states.sensor.dark_sky_overnight_low_temperature.state|round}} degrees. Amys travel time to work is currently {{states.sensor.amy_waze_to_work.state}} minutes. Bills travel time to work is currently {{states.sensor.bill_waze_to_work.state}} minutes. Time to get in the shower!'

- alias: Morning Radio 2
  trigger:
    - platform: time
      at: '06:56:50'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: '0.12'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroom_speaker
        media_content_id: http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_one.m3u8
        media_content_type: 'application/x-mpegurl'


###Morning Lighting###
- alias: Morning Lights
  trigger:
    - platform: time
      at: '06:55:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bill_bedside_light
          - light.amy_bedside_light
        transition: 1200
        kelvin: 2700


#- alias: Weekend Lights
#  trigger:
#    - platform: time
#      at: '08:15:00'
#  condition:
#    - condition: time
#      weekday:
#        - sat
#        - sun
#    - condition: sun
#      before: sunrise
#  action:
#    - service: light.turn_on
#      data:
#        entity_id:
#          - light.bill_bedside_light
#          - light.amy_bedside_light
#        transition: 1200
#        kelvin: 2700
