###Cat Heater Schedule###
- alias: Cat AM ON
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      below: 8
    - condition: numeric_state
      entity_id: sensor.dark_sky_daytime_high_temperature
      below: 12
  action:
    - service: switch.turn_on
      entity_id: switch.space_heater

- alias: Cat AM OFF
  trigger:
    platform: time
    at: '08:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.space_heater

- alias: Cat PM ON
  trigger:
    platform: time
    at: '15:30:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      below: 8
    - condition: numeric_state
      entity_id: sensor.dark_sky_daytime_high_temperature
      below: 12
  action:
    - service: switch.turn_on
      entity_id: switch.space_heater

- alias: Cat PM OFF
  trigger:
    platform: time
    at: '16:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.space_heater

- alias: Cat Timeout
  trigger:
    platform: state
    entity_id: switch.space_heater
    to: 'on'
  action:
    - delay: '02:00:00'
    - service: switch.turn_off
      entity_id: switch.space_heater
    
