###Common Area Automations###


###Front Door Automations###
- alias: Front Door On
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    - platform: state
      entity_id: device_tracker.google_maps_113840736270482299573
      to: 'home'
  condition:
    - condition: sun
      after: sunset
      after_offset: '-02:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.porch_light
        kelvin: 3600
        brightness_pct: 100


- alias: Front Door for Strangers
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_PIR_sensor
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: '-01:00:00'
    - condition: time
      before: '23:59:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.porch_light
        kelvin: 3600
        brightness_pct: 100
    - delay: '00:02:00'
    - service: light.turn_off
      data:
        entity_id: light.porch_light


- alias: Front Door Off
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'off'
  action:
    - delay: '00:02:00'
    - service: light.turn_off
      data:
        entity_id: light.porch_light


- alias: Front Door Timeout
  trigger:
    - platform: state
      entity_id: light.porch_light
      to: 'on'
  action:
    - delay: '00:15:00'
    - service: light.turn_off
      data:
        entity_id: light.porch_light


###Hallway Automations###
- alias: Hallway On
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.hall_door
      to: 'on'
#  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_light
        kelvin: 3600
        brightness_pct: 100


- alias: Hallway Off
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'off'
    - platform: state
      entity_id: binary_sensor.hall_door
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.front_door
      state: 'off'
    - condition: state
      entity_id: binary_sensor.hall_door
      state: 'off'
  action:
    - delay: '00:03:00'
    - service: light.turn_off
      data:
        entity_id: light.hall_light


- alias: Hallway Timeout
  trigger:
    - platform: state
      entity_id: light.hall_light
      to: 'on'
  action:
    - delay: '00:15:00'
    - service: light.turn_off
      data:
        entity_id: light.hall_light
