### Home time###
- alias: Home time
  trigger:
    - platform: state
      entity_id: device_tracker.amysiphone
      to: 'home'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      after: '16:00:00'
      before: '18:15:00'
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/power"
        payload: "ON"
#    - delay: '00:02:30'
#    - service: tts.google_say
#      entity_id: media_player.living_room_speaker
#      data:
#        message: 'Welcome home Amy!'

      

#- alias: Home time end dumb
#  trigger:
#    - platform: time
#      at: '19:30:00'
#  action:
#    - service: mqtt.publish
#      data:
#        topic: "cmnd/sonoff/power"
#        payload: "OFF"

- alias: Home time end
  trigger:
    - platform: state
      entity_id: switch.scentsy
      to: 'on'
  action:
    - delay: '02:00:00'
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/power"
        payload: "OFF"

###Living Room Lamp###
- alias: Lamp light on
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lamp

- alias: Lamp light off
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_lamp
